# Generated by Django 6.0.2 on 2026-02-16 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='is_featured',
            new_name='featured',
        ),
        migrations.RemoveField(
            model_name='category',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project'),
        ),
    ]
